INSERT INTO sintoma(nome_sintoma)VALUES ('Febre alta');
INSERT INTO sintoma(nome_sintoma)VALUES ('Cefaleia');
INSERT INTO sintoma(nome_sintoma)VALUES ('Dor retroorbitária');
INSERT INTO sintoma(nome_sintoma)VALUES ('Mialgia');
INSERT INTO sintoma(nome_sintoma)VALUES ('Artralgia');
INSERT INTO sintoma(nome_sintoma)VALUES ('Náuseas');
INSERT INTO sintoma(nome_sintoma)VALUES ('Vômitos');
INSERT INTO sintoma(nome_sintoma)VALUES ('Diarreia');
INSERT INTO sintoma(nome_sintoma)VALUES ('Exantema');
INSERT INTO sintoma(nome_sintoma)VALUES ('Manifestações hemorrágicas');
INSERT INTO sintoma(nome_sintoma)VALUES ('Febre hemorrágica da dengue (FHD)');
INSERT INTO sintoma(nome_sintoma)VALUES ('Síndrome do choque por dengue (SCD)');
INSERT INTO sintoma(nome_sintoma)VALUES ('Febre');
INSERT INTO sintoma(nome_sintoma)VALUES ('Mal-estar');
INSERT INTO sintoma(nome_sintoma)VALUES ('Inchaço de um olho');
INSERT INTO sintoma(nome_sintoma)VALUES ('Inchaço e vermelhidão no local da picada do inseto');
INSERT INTO sintoma(nome_sintoma)VALUES ('Fadiga');
INSERT INTO sintoma(nome_sintoma)VALUES ('Irritação sobre a pele');
INSERT INTO sintoma(nome_sintoma)VALUES ('Dores no corpo');
INSERT INTO sintoma(nome_sintoma)VALUES ('Dor de cabeça');
INSERT INTO sintoma(nome_sintoma)VALUES ('Surgimento de nódulos');
INSERT INTO sintoma(nome_sintoma)VALUES ('Aumento do tamanho do fígado');
INSERT INTO sintoma(nome_sintoma)VALUES ('Aumento do tamanho do baço');
INSERT INTO sintoma(nome_sintoma)VALUES ('calafrios');
INSERT INTO sintoma(nome_sintoma)VALUES ('suores');
INSERT INTO sintoma(nome_sintoma)VALUES ('fraqueza');
INSERT INTO sintoma(nome_sintoma)VALUES ('falta de apetite');
INSERT INTO sintoma(nome_sintoma)VALUES ('tosse');
INSERT INTO sintoma(nome_sintoma)VALUES ('Tonturas');
INSERT INTO sintoma(nome_sintoma)VALUES ('Sensação de plenitude gástrica');
INSERT INTO sintoma(nome_sintoma)VALUES ('Prurido (coceira) anal');
INSERT INTO sintoma(nome_sintoma)VALUES ('palpitações');
INSERT INTO sintoma(nome_sintoma)VALUES ('Impotência');
INSERT INTO sintoma(nome_sintoma)VALUES ('Emagrecimento');
INSERT INTO sintoma(nome_sintoma)VALUES ('Endurecimento do fígado');
INSERT INTO sintoma(nome_sintoma)VALUES ('Olhos, face ou língua avermelhada');
INSERT INTO sintoma(nome_sintoma)VALUES ('Fotofobia');
INSERT INTO sintoma(nome_sintoma)VALUES ('');
INSERT INTO sintoma(nome_sintoma)VALUES ('');


